### ISSUE TITLE
Adding a license for racer?

### ISSUE THREAD

**Issue by hr-oss** [jaammees/racer#1]
Hi @jaammees ! I know I'm five or so years late, but Racer is a solid game! I was curious, were you planning on perhaps adding a license to this repo? I was thinking of making a fork of it, but only in your good graces :) If you'd like to, here is the documentation for licensing this repo! https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by RockinPaul** [comment]
James has passed away.
https://github.com/jaammees/lvllvl/issues/1#issuecomment-1965312594

**Comment by hr-oss** [comment]
Oh, I'm very sorry to hear that--thank you for the update, Paul. 😞
